name: Proxy Update

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"  # 每天执行一次，可以根据需要修改执行时间
  workflow_dispatch:

permissions:
  contents: write  # 允许该动作推送修改到仓库

jobs:
  update_proxy_list:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq curl

    - name: Fetch proxy list
      run: |
        curl -s https://cb-x2-jun.github.io/proxy-lists/proxies.json -o proxies.json

    - name: Filter and format proxies
      run: |
        jq '{proxy_list: [.[] | select(.protocol == "https") | {host: (.ip + ":" + (.port|tostring)), country: .country, quality: 4} ]}' proxies.json > pxy.json


    - name: Commit and push updated proxy list
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"
        git add pxy.json
        git commit -m "Update proxy list"
        git push

